### ISSUE TITLE
Window minimize(), restore() not working on macOS X (Mojave): Error: A boolean was expected!

### ISSUE THREAD

**Issue by ahkohd** [sentialx/node-window-manager#16]
While I was testing stuff out on macOS X (Mojave), the ``window.minimize()`` and ``window.restore()`` failed and spilled out some errors.

```ts
const { windowManager } = require("node-window-manager");
const current = windowManager.getActiveWindow();
console.log(current);
current.minimize();
```

Error Thrown:
```
Error: A boolean was expected
    at Window.minimize (/Users/victor/Documents/switch/switch/node_modules/node-window-manager/dist/classes/window.js:82:19)
    at Object.<anonymous> (/Users/victor/Documents/switch/switch/build/test.js:4:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```
Am trying to investigate what happened. 😖

**Comment by ahkohd** [comment]
I dived into ``macos.mm``and there lies the bug, I will make a pull request soon to fix it.

**Edit**
I have already made the PR #17
