### ISSUE TITLE
Install fails on windows with error in extract-file-icons

### ISSUE THREAD

**Issue by JoCa96** [sentialx/node-window-manager#59]
**Bug description**

I am trying to build our electron app with this package on a windows agent.
Unfortunately the installation fails with the following error.

```
8734 verbose lifecycle extract-file-icon@0.3.2~install: CWD: D:\a\1\buildsources\packages\launchpad-native\node_modules\extract-file-icon
8735 silly lifecycle extract-file-icon@0.3.2~install: Args: [ '/d /s /c', 'npm run rebuild' ]
8736 silly lifecycle extract-file-icon@0.3.2~install: Returned: code: 1  signal: null
8737 info lifecycle extract-file-icon@0.3.2~install: Failed to exec install script
8738 verbose teardown shutting down workers.
8739 info teardown Done in 0s
8740 verbose stack Error: extract-file-icon@0.3.2 install: `npm run rebuild`
8740 verbose stack Exit status 1
8740 verbose stack     at EventEmitter.<anonymous> (C:\hostedtoolcache\windows\node\14.19.0\x64\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
8740 verbose stack     at EventEmitter.emit (events.js:400:28)
8740 verbose stack     at ChildProcess.<anonymous> (C:\hostedtoolcache\windows\node\14.19.0\x64\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
8740 verbose stack     at ChildProcess.emit (events.js:400:28)
8740 verbose stack     at maybeClose (internal/child_process.js:1058:16)
8740 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
8741 verbose pkgid extract-file-icon@0.3.2
8742 verbose cwd D:\a\1\buildsources\packages\launchpad-native
8743 verbose Windows_NT 10.0.20348
8744 verbose argv "C:\\hostedtoolcache\\windows\\node\\14.19.0\\x64\\node.exe" "C:\\hostedtoolcache\\windows\\node\\14.19.0\\x64\\node_modules\\npm\\bin\\npm-cli.js" "ci"
8745 verbose node v14.19.0
8746 verbose npm  v6.14.16
8747 error code ELIFECYCLE
8748 error errno 1
8749 error extract-file-icon@0.3.2 install: `npm run rebuild`
8749 error Exit status 1
8750 error Failed at the extract-file-icon@0.3.2 install script.
8750 error This is probably not a problem with npm. There is likely additional logging output above.
8751 verbose exit [ 1, true ]

##[error]Error: Npm failed with return code: 1
```

**Details:**
 - Operating System: windows-latest
 - `node-window-manager` version: 2.2.4
 - Last known working `node-window-manager` version: -

**Additional context**
The installation works on MacOS

**Comment by JoCa96** [comment]
We use Azure DevOps. We figured out, that switching back to the [windows-2019](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#software) agent works around the issue.
Microsoft recently switched the "windows-latest" from "windows-2019" to "windows-2022", that explains why it suddenly stopped working.

**Comment by KhalilSelyan** [comment]
Any current fix to this issues ? as i'm running this on my own machine, rolling back OS version is not an option
